name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["core"]
jobs:
  continuous_integration_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_game_of_life
        uses: actions/checkout@v4
        with:
          path: game_of_life
      - name: checkout_cexil
        uses: actions/checkout@v4
        with:
          repository: alic3dev/cexil
          path: cexil
      - name: checkout_interrupt_handler
        uses: actions/checkout@v4
        with:
          repository: alic3dev/interrupt_handler
          path: interrupt_handler
      - name: make_cexil
        run: cd cexil && make
      - name: make_interrupt_handler
        run: cd interrupt_handler && make
      - name: make_game_of_life
        run: cd game_of_life && CEXIL_DIRECTORY=../cexil INTERRUPT_HANDLER_DIRECTORY=../interrupt_handler make
